layout_spectrum: 0.8781362
color:
  saturation: 0.3915923
  lightness: 0.3362289
  brandStrength: 0.4370577
  rhythmicContrast: 0.1928382
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
typography_spectrum: 0.4007885
name: CityboyBushcraft
